[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
de_anno_token_program = "2ckWV1BszPt6hwfjyLP4FMSrR4zxbYhkXbnJcDWpq4Q7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/Code/07_Solana/.Solana_wallet/test_wallet_1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
